services:
  db:
    image: bitnami/postgresql:latest
    environment:
      - POSTGRESQL_USERNAME=root
      - POSTGRESQL_PASSWORD=docker
      - POSTGRESQL_DATABASE=picpay
    ports:
      - '5432:5432'
  redis:
    image: 'bitnami/redis:latest'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    ports: 
      - '6379:6379'
      